// Software Rendering Pipeline (SRP) library
// Licensed under GNU GPLv3

/** @file
 *  @ingroup Context
 *  Message callback declaration and helper functions */

#pragma once

/** @ingroup Context
 *  @{ */

/** Represents the message type (error, warning, etc.) @see `SRPMessageCallback` */
typedef enum SRPMessageType
{
	SRP_MESSAGE_ERROR,
	SRP_MESSAGE_WARNING
} SRPMessageType;

/** Represents the message severity @see `SRPMessageCallback` */
typedef enum SRPMessageSeverity
{
	SRP_MESSAGE_SEVERITY_LOW,       /**< Low severity */
	SRP_MESSAGE_SEVERITY_MODERATE,  /**< Moderate severity */
	SRP_MESSAGE_SEVERITY_HIGH       /**< High severity */
} SRPMessageSeverity;

/** A function of this type may be defined by user to handle the messages
 *  generated by the library (errors, warnings, etc.) @see `SRPContext`
 * 	@param[in] type The type of the message
 *  @param[in] severity Severity of the message
 *  @param[in] sourceFunction String containing the name of the function which issued this callback
 *  @param[in] message Message sent
 *  @param[in] userParameter User paramter pointer. @see `SRPMessageCallback.userParameter`
 * */
typedef void (*SRPMessageCallbackFunc)(
	SRPMessageType type, SRPMessageSeverity severity, const char* sourceFunction,
	const char* message, void* userParameter
);

typedef struct SRPMessageCallback
{
	SRPMessageCallbackFunc func;  /**< Function that is called whenever an error/warning/etc. occurs */
	void* userParameter;          /**< User pointer to pass to message callback function */
} SRPMessageCallback;

/** @} */  // ingroup Context
