// Software Rendering Pipeline (SRP) library
// Licensed under GNU GPLv3

/** @file
 *  Message callback declaration and helper functions */

#pragma once

/** @ingroup Context
 *  @{ */

/** Represents the message type (error, warning, etc.) @see `SRPMessageCallbackType` */
typedef enum MessageType
{
	SRP_MESSAGE_ERROR,
	SRP_MESSAGE_WARNING
} SRPMessageType;

/** Represents the message severity @see `SRPMessageCallbackType` */
typedef enum MessageSeverity
{
	SRP_MESSAGE_SEVERITY_LOW,
	SRP_MESSAGE_SEVERITY_MODERATE,
	SRP_MESSAGE_SEVERITY_HIGH
} SRPMessageSeverity;

/** A function of this type may be defined by user to handle the messages
 *  generated by the library (errors, warnings, etc.) @see `SRPContext` */
typedef void (*SRPMessageCallbackType)(
	SRPMessageType type, SRPMessageSeverity severity, const char* sourceFunction,
	const char* message, void* userParameter
);

/** @} */  // ingroup Context

